import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, expect, it, vi } from 'vitest'
import { ServiceAllowanceConfiguration as ServiceAllowances, ServiceAllowances as AllowancePage } from '../service-allowances'
import { adminRequest } from '@/lib/api'
vi.mock('@/lib/api', () => ({ adminRequest: vi.fn() }))
const rule = { enabled: false, mode: 'quota', unit: 'requests', period: 'month', limit: 0, revision: 0, approval_operations: [], denied_operations: [] }
const item = { service: 'test', name: '测试服务', rule, spent: 0, reserved: 0, remaining: 0, pending: [] }
beforeEach(() => vi.mocked(adminRequest).mockReset())
it('starts disabled and writes only after explicit human save', async () => {
  vi.mocked(adminRequest).mockResolvedValue([item])
  const user = userEvent.setup()
  render(<ServiceAllowances adminToken='' />)
  const enabled = await screen.findByRole('switch', { name: '启用此服务的自主使用限制' })
  expect(enabled).not.toBeChecked()
  expect(adminRequest).toHaveBeenCalledTimes(1)
  await user.click(enabled)
  await user.clear(screen.getByLabelText('总额度')); await user.type(screen.getByLabelText('总额度'), '10')
  await user.type(screen.getByLabelText('始终需要批准的操作'), 'delete, payment')
  expect(adminRequest).toHaveBeenCalledTimes(1)
  await user.click(screen.getByRole('button', { name: '保存配置' }))
  await waitFor(() => expect(adminRequest).toHaveBeenCalledWith('/local/api/service-allowances/test', '', expect.objectContaining({ method: 'PUT' })))
  const init = vi.mocked(adminRequest).mock.calls[1][2]
  expect(JSON.parse(String(init?.body))).toMatchObject({ enabled: true, limit: 10, approval_operations: ['delete', 'payment'] })
})
it('reports persistence failure without showing success', async () => {
  vi.mocked(adminRequest).mockResolvedValueOnce([item]).mockRejectedValueOnce(new Error('磁盘写入失败'))
  const user = userEvent.setup(); render(<ServiceAllowances adminToken='' />)
  await user.click(await screen.findByRole('button', { name: '保存配置' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('磁盘写入失败')
  expect(screen.queryByText('规则已保存，额度功能关闭。')).not.toBeInTheDocument()
})
it('accepts fractional dollar limits without losing the decimal point', async () => {
  vi.mocked(adminRequest).mockResolvedValue([item])
  const user = userEvent.setup(); render(<ServiceAllowances adminToken='' />)
  await user.selectOptions(await screen.findByLabelText('计量单位'), 'usd_micros')
  await user.clear(screen.getByLabelText('总额度')); await user.type(screen.getByLabelText('总额度'), '0.25')
  await user.click(screen.getByRole('button', { name: '保存配置' }))
  await waitFor(() => expect(adminRequest).toHaveBeenCalledTimes(3))
  expect(JSON.parse(String(vi.mocked(adminRequest).mock.calls[1][2]?.body))).toMatchObject({ unit: 'usd_micros', limit: 250000 })
})
it('shows saved configuration amounts independently of activation and distinguishes defaults', async () => {
  const other = { ...item, service: 'image', name: '图像服务', rule: { ...rule, enabled: true, limit: 10, revision: 1 }, spent: 2, reserved: 3, remaining: 5, pending: [{ id: 'receipt-1', operation: 'create', token_id: 2, amount: 3 }] }
  vi.mocked(adminRequest).mockResolvedValue([{ ...item, rule: { ...rule, unit: 'usd_micros', limit: 3000000, revision: 1, operation_limits: { search: 1000000 } }, remaining: 3000000 }, other, { ...item, service: 'unconfigured', name: '未配置服务', rule: { ...rule, unit: 'usd_micros', limit: 3000000 } }, { ...item, service: 'zero', name: '零额度服务', rule: { ...rule, revision: 1 } }])
  const user = userEvent.setup(); render(<ServiceAllowances adminToken='' />)
  expect(await screen.findByRole('button', { name: '测试服务 自主额度' })).toHaveAttribute('aria-current', 'page')
  expect(screen.getByRole('button', { name: '测试服务 自主额度' })).toHaveTextContent('$3')
  expect(screen.getByRole('button', { name: '未配置服务 自主额度' })).toHaveTextContent('未配置')
  expect(screen.getByRole('button', { name: '未配置服务 自主额度' })).not.toHaveTextContent('$3')
  expect(screen.getByRole('button', { name: '零额度服务 自主额度' })).toHaveTextContent('0 次')
  expect(screen.getByRole('button', { name: '图像服务 自主额度' })).toHaveTextContent('10 次')
  expect(screen.getByRole('button', { name: '图像服务 自主额度' })).not.toHaveTextContent('5 次')
  expect(screen.getByRole('region', { name: '当前服务额度' })).toHaveTextContent('配置额度$3')
  expect(screen.queryByRole('combobox', { name: '服务' })).not.toBeInTheDocument()
  await user.type(screen.getByRole('textbox', { name: '搜索额度服务' }), '图像')
  expect(screen.queryByRole('button', { name: '测试服务 自主额度' })).not.toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: '图像服务 自主额度' }))
  expect(screen.getByRole('heading', { name: '图像服务' })).toBeInTheDocument()
  expect(screen.getByLabelText('总额度')).toHaveValue(10)
  expect(screen.getByRole('region', { name: '当前服务额度' })).toHaveTextContent('配置额度10 次')
  expect(screen.getByRole('switch', { name: '启用此服务的自主使用限制' })).toBeChecked()
  expect(adminRequest).toHaveBeenCalledTimes(1)
})
it('batch-fills independent operation limits at three dollars without enabling the service', async () => {
  const dollarItem = { ...item, rule: { ...rule, unit: 'usd_micros', limit: 3000000 }, operations: ['search', 'generate'].map(id => ({ id, name: id, configured: false, limit: 0, spent: 0, reserved: 0, remaining: 0 })) }
  vi.mocked(adminRequest).mockResolvedValue([dollarItem])
  const user = userEvent.setup(); render(<ServiceAllowances adminToken='' />)
  await user.click(await screen.findByRole('checkbox', { name: '选择全部筛选操作' }))
  await user.click(screen.getByRole('button', { name: '填入已选 (2)' }))
  expect(screen.getByRole('spinbutton', { name: 'search 子额度' })).toHaveValue(3)
  expect(screen.getByRole('spinbutton', { name: 'generate 子额度' })).toHaveValue(3)
  expect(adminRequest).toHaveBeenCalledTimes(1)
  await user.click(screen.getByRole('button', { name: '保存配置' }))
  await waitFor(() => expect(adminRequest).toHaveBeenCalledTimes(3))
  expect(JSON.parse(String(vi.mocked(adminRequest).mock.calls[1][2]?.body))).toMatchObject({ enabled: false, operation_limits: { search: 3000000, generate: 3000000 } })
})
it('saves multiple service limits atomically and preserves their enabled states', async () => {
  vi.mocked(adminRequest).mockResolvedValue([item, { ...item, service: 'second', name: '另一服务', rule: { ...rule, enabled: true } }])
  const user = userEvent.setup(); render(<ServiceAllowances adminToken='' />)
  await user.click(await screen.findByRole('checkbox', { name: '选择服务 测试服务' }))
  expect(screen.getByRole('checkbox', { name: '选择全部筛选服务' })).toBePartiallyChecked()
  await user.click(screen.getByRole('button', { name: '批量设置 (1)' }))
  await user.click(screen.getByRole('checkbox', { name: '批量选择 另一服务' }))
  expect(screen.getByRole('spinbutton', { name: '每个服务的总额度' })).toHaveValue(3)
  await user.click(screen.getByRole('button', { name: '保存批量额度' }))
  await waitFor(() => expect(adminRequest).toHaveBeenCalledTimes(3))
  expect(vi.mocked(adminRequest).mock.calls[1][0]).toBe('/local/api/service-allowances/batch')
  const body = JSON.parse(String(vi.mocked(adminRequest).mock.calls[1][2]?.body))
  expect(body.services.map((entry: { rule: { limit: number; enabled: boolean; unit: string } }) => [entry.rule.limit, entry.rule.enabled, entry.rule.unit])).toEqual([[3000000, false, 'usd_micros'], [3000000, true, 'usd_micros']])
})

it('keeps the whole feature collapsed until the human enables it and persists off', async () => {
  vi.mocked(adminRequest).mockResolvedValueOnce({ enabled: false, revision: 0 })
    .mockResolvedValueOnce({ enabled: true, revision: 1 }).mockResolvedValueOnce([item])
    .mockResolvedValueOnce({ enabled: false, revision: 2 })
  const user = userEvent.setup(); render(<AllowancePage adminToken='' />)
  const toggle = await screen.findByRole('switch', { name: '启用自主额度' })
  await waitFor(() => expect(toggle).toBeEnabled())
  expect(toggle).not.toBeChecked()
  expect(screen.queryByRole('textbox', { name: '搜索额度服务' })).not.toBeInTheDocument()
  expect(adminRequest).toHaveBeenCalledTimes(1)
  await user.click(toggle)
  expect(await screen.findByRole('textbox', { name: '搜索额度服务' })).toBeInTheDocument()
  expect(toggle).toBeChecked()
  expect(JSON.parse(String(vi.mocked(adminRequest).mock.calls[1][2]?.body))).toEqual({ enabled: true, revision: 0 })
  await user.click(toggle)
  await waitFor(() => expect(toggle).not.toBeChecked())
  expect(screen.queryByRole('textbox', { name: '搜索额度服务' })).not.toBeInTheDocument()
  expect(JSON.parse(String(vi.mocked(adminRequest).mock.calls[3][2]?.body))).toEqual({ enabled: false, revision: 1 })
})
it('does not reveal configuration when enabling fails', async () => {
  vi.mocked(adminRequest).mockResolvedValueOnce({ enabled: false, revision: 2 }).mockRejectedValueOnce(new Error('配置已变更'))
  const user = userEvent.setup(); render(<AllowancePage adminToken='' />)
  const toggle = await screen.findByRole('switch', { name: '启用自主额度' })
  await waitFor(() => expect(toggle).toBeEnabled())
  await user.click(toggle)
  expect(await screen.findByRole('alert')).toHaveTextContent('配置已变更')
  expect(toggle).not.toBeChecked()
  expect(screen.queryByRole('textbox', { name: '搜索额度服务' })).not.toBeInTheDocument()
})
